version: "2"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: antriksh
    build: .
    command: npm run serve
    ports:
      - "3031:3031"
    networks:
      - webnet
networks:
  webnet:
